set nocompatible
filetype off

set rtp+=$HOME/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

let &t_Co=256
syntax enable

" all about surroundings
Bundle 'surround.vim'

" realtime keyword completion
Bundle 'Shougo/neocomplcache'
let g:neocomplcache_enable_at_startup = 1

" information widget
Bundle 'Shougo/unite.vim'

Bundle 'kana/vim-fakeclip'

Bundle 'vim-scripts/guicolorscheme.vim'

" color schema
Bundle 'tomasr/molokai'
Bundle 'vim-scripts/Zenburn'
Bundle 'vim-scripts/Solarized'

""" Javascript bundles
" syntax highlight
Bundle 'JavaScript-syntax'

" indent
Bundle 'pangloss/vim-javascript'

""" Python bundles
" syntax and style cheker
Bundle 'nvie/vim-flake8'

" completion
Bundle 'pythoncomplete'

" module and class doc viewer
Bundle 'fs111/pydoc.vim'

" refactoring tools
" Bundle 'sontek/rope-vim'

nnoremap ; :
" Edit .vimrc
nnoremap <silent> <Space>ev  :<C-u>edit $MYVIMRC<CR>
" Load .vimrc
nnoremap <silent> <Space>rv :<C-u>source $MYVIMRC<CR>

set hlsearch
set incsearch

nnoremap <C-a> 0
nnoremap <C-e> $
nnoremap <C-k> d$

""" Unite.vim
" 起動時にインサートモードで開始
let g:unite_enable_start_insert = 1

" インサート／ノーマルどちらからでも呼び出せるようにキーマップ
nnoremap <silent> <C-f> :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
inoremap <silent> <C-f> <ESC>:<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> <C-b> :<C-u>Unite buffer file_mru<CR>
inoremap <silent> <C-b> <ESC>:<C-u>Unite buffer file_mru<CR>

set wildmode=list:longest
filetype plugin indent on
set background=dark
colorscheme Zenburn
"autocmd VimEnter * :GuiColorScheme Zenburn
