set nocompatible
filetype off

set rtp+=$HOME/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

let &t_Co=256
syntax enable

" all about surroundings
Bundle 'surround.vim'

" realtime keyword completion
Bundle 'Shougo/neocomplcache'
let g:neocomplcache_enable_at_startup = 1

" information widget
Bundle 'Shougo/unite.vim'
" start with insert mode
let g:unite_enable_start_insert = 1
nnoremap <silent> <C-f> :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
inoremap <silent> <C-f> <ESC>:<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> <C-b> :<C-u>Unite buffer file_mru<CR>
inoremap <silent> <C-b> <ESC>:<C-u>Unite buffer file_mru<CR>


" convert variable name style
" commands:
" crc -> hogeHoge
" crm -> HogeHoge
" cr_ -> hoge_hoge
" crs -> hoge_hoge
" cru -> HOGE_HOGE
Bundle 'tpope/vim-abolish'

Bundle 'kana/vim-fakeclip'

" textobj extension
Bundle 'kana/vim-textobj-user'

" treat indent as textobj
Bundle 'kana/vim-textobj-indent'

" comment out
Bundle 'tomtom/tcomment_vim'

" reference
Bundle 'thinca/vim-ref'

Bundle 'vim-scripts/guicolorscheme.vim'

" color schema
Bundle 'tomasr/molokai'
Bundle 'vim-scripts/Zenburn'
colorscheme zenburn
Bundle 'vim-scripts/Solarized'

""" Javascript bundles
" syntax highlight
Bundle 'JavaScript-syntax'

" indent
Bundle 'pangloss/vim-javascript'

""" Python bundles
" syntax and style cheker
Bundle 'nvie/vim-flake8'

" completion
Bundle 'pythoncomplete'

" module and class doc viewer
Bundle 'fs111/pydoc.vim'

" refactoring tools
" Bundle 'sontek/rope-vim'

nnoremap ; :
" Edit .vimrc
nnoremap <silent> <Space>ev  :<C-u>edit $MYVIMRC<CR>
" Load .vimrc
nnoremap <silent> <Space>rv :<C-u>source $MYVIMRC<CR>

setl tabstop=8
setl softtabstop=4
setl shiftwidth=4
setl smarttab
setl expandtab
set hlsearch
set incsearch

nnoremap <ESC><ESC> :nohlsearch<CR>

nnoremap <C-a> 0
nnoremap <C-e> $
nnoremap <C-k> d$

vnoremap < <gv
vnoremap > >gv

set tags=~/.tags

set wildmode=list:longest
filetype plugin indent on
set background=dark
"autocmd VimEnter * :GuiColorScheme Zenburn
